flags: {}
user-message: ! 'Warning (added by new or init): Some packages were found to have
  names conflicting with others and have been commented out in the packages section.

  Warning (added by new or init): Specified resolver could not satisfy all dependencies.
  Some external packages have been added as dependencies.

  You can suppress this message by removing it from stack.yaml

'
packages:
- fun/equ
- fun
- hal
- .
extra-deps:
- combinat-0.2.8.2
- gtksourceview2-0.13.3.1
- reference-0.1
resolver: lts-9.6
