char* prohibited[] = {"bourgeois", "BOURGEOIS", "Bourgeois", "bourgeoisieclass",
                "BOURGEOISIECLASS", "Bourgeoisieclass", "communism", "COMMUNISM",
                "Communism", "communist", "COMMUNIST", "Communist", "communists",
                "COMMUNISTS", "Communists", "communistic", "COMMUNISTIC","Communistic", 
                "conservative", "CONSERVATIVE", "Conservative","country", "COUNTRY", 
                "Country", "countries", "COUNTRIES","Countries", "family", "FAMILY",
                "Family", "free", "FREE", "Free","freedom", "FREEDOM", "Freedom", "history",
                "HISTORY", "History","historical", "HISTORICAL", "Historical", "justice", 
                "JUSTICE","Justice", "moral", "MORAL", "Moral", "philosophy", "PHILOSOPHY",
                "Philosophy", "philosophical", "PHILOSOPHICAL", "Philosophical","politic", 
                "POLITIC", "Politic", "politics", "POLITICS","Politics", "political", "POLITICAL",
                "Political", "proletarian","PROLETARIAN", "Proletarian", "proletariat", "PROLETARIAT",
                "Proletariat", "radical", "RADICAL", "Radical", "religion","RELIGION", "Religion", 
                "religions", "RELIGIONS", "Religions","religious", "RELIGIOUS", "Religious", "social",
                "SOCIAL","Social", "socialism", "SOCIALISM", "Socialism", "socialist","SOCIALIST", 
                "Socialist", "socialists", "SOCIALISTS","Socialists", "society", "SOCIETY", "Society", 
                "value", "VALUE","Value", "world", "WORLD", "World", "work", "WORK", "Work","working-class", 
                "WORKING-CLASS", "Working-class","Friederich", "Engels"};